### ISSUE TITLE
Local file changes are being uploaded on save but not triggering a version control change

### ISSUE THREAD

**Issue by mcowart123** [paiqo/Databricks-VSCode#123] opened 2023-01-13 15:46 UTC
When I make changes locally to a file after saving they are uploaded immediately like they should be. Viewing in the editor on the web shows the changed text of the file.

The only problem is when I go to commit the changes it doesn't show any having being made. This is confusing at best and could be disastrous at worst if you're not paying attention and think something has been committed when it actually hasn't.

**Comment by gbrueckl** [comment] 2023-02-07 21:26
the issue is confirmed by Databricks but there is no solution yet

**Comment by gbrueckl** [comment] 2023-04-24 11:55
this should be fixed for quite some time now
i also ran a test on my own and it worked

could you please also test again and close this ticket if it is resolved?

**Comment by mcowart123** [comment] 2023-04-24 22:22
It will probably be a week before I can get a chance to test this.

**Comment by gbrueckl** [comment] 2023-04-25 13:41
no worries, just update me here so I know whether we can close this ticket or not

**Comment by gbrueckl** [comment] 2023-09-28 18:44
just ran some tests and this should be fixed now

**Closed by gbrueckl** 2023-09-28 18:44 UTC
