### ISSUE TITLE
Fail to use connection from Notebook

### ISSUE THREAD

**Issue by petervandenabeele** [paiqo/Databricks-VSCode#44] opened 2020-12-04 19:54 UTC
Thanks for the plug-in to vsCode, but I am puzzled ...

I can make a connection to a running Databricks cluster (on AWS),
I can run Spark code as a simple pySpark program on the cluster (and that is clearly running on the databricks cluster)
I can see, download notebooks on my databricks account

But when I open a Notebook in the editor, for the Jupyter server, I can only select either:
* "Default", which is a local notebook server
* "Existing", but I have no idea what I would need to write there to use my "green"connection.
(I am offered this `https://hostname:8080/?token=849d61a414abafab97bc4aab1f3547755ddc232c2b8cb7fe`
but I am strongly presuming that is not a really activce URL ...).

What should I do to connect the Notebook to the Databricks cluster ?

Looking in outpyut Log (Window), I see many errors of the type below.
I do not understand how I could set these keys and I do not see them in Properties > Settings:

* databricks.connection.default.databricksConnectJars
* databricks.connection.default.pythonInterpreter
* databricks.connection.default.organizationId

In my ` databricks-connect.exe configure` I have them available:

In Git bash shell, I see this:
```
USER____@LA____ MINGW64 ~/code/BD/vscode-databricks (master)
$ databricks-connect.exe get-jar-dir
c:\users\user____\.virtualenvs\vscode-databricks-97usnpxs\lib\site-packages\pyspark/jars
```
I will try to add a screen shot here too.

Thanks :-)

````
[2020-12-04 20:35:57.600] [renderer1] [error] Unable to write to Workspace Settings because databricks.connection.default.databricksConnectJars is not a registered configuration.: Error: Unable to write to Workspace Settings because databricks.connection.default.databricksConnectJars is not a registered configuration.
    at k.reject (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5789:245)
    at k.resolveAndValidate (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5792:159)
    at k.doWriteConfiguration (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5786:275)
    at Object.factory (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5786:51)
    at u.consume (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:75)
    at u.consumed (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:236)
    at file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:117
[2020-12-04 20:35:57.600] [renderer1] [error] Unable to write to Workspace Settings because databricks.connection.default.pythonInterpreter is not a registered configuration.: Error: Unable to write to Workspace Settings because databricks.connection.default.pythonInterpreter is not a registered configuration.
    at k.reject (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5789:245)
    at k.resolveAndValidate (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5792:159)
    at k.doWriteConfiguration (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5786:275)
    at Object.factory (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5786:51)
    at u.consume (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:75)
    at u.consumed (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:236)
    at file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:137
[2020-12-04 20:35:57.600] [renderer1] [error] Unable to write to Workspace Settings because databricks.connection.default.port is not a registered configuration.: Error: Unable to write to Workspace Settings because databricks.connection.default.port is not a registered configuration.
    at k.reject (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5789:245)
    at k.resolveAndValidate (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5792:159)
    at k.doWriteConfiguration (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5786:275)
    at Object.factory (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5786:51)
    at u.consume (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:75)
    at u.consumed (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:236)
    at file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:137
[2020-12-04 20:35:57.601] [renderer1] [error] Unable to write to Workspace Settings because databricks.connection.default.organizationId is not a registered configuration.: Error: Unable to write to Workspace Settings because databricks.connection.default.organizationId is not a registered configuration.
    at k.reject (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5789:245)
    at k.resolveAndValidate (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5792:159)
    at k.doWriteConfiguration (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5786:275)
    at Object.factory (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5786:51)
    at u.consume (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:75)
    at u.consumed (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:236)
    at file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:137
[2020-12-04 20:35:57.601] [renderer1] [error] Unable to write to Workspace Settings because python.dataScience.codeRegularExpression is not a registered configuration.: Error: Unable to write to Workspace Settings because python.dataScience.codeRegularExpression is not a registered configuration.
    at k.reject (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5789:245)
    at k.resolveAndValidate (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5792:159)
    at k.doWriteConfiguration (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5786:275)
    at Object.factory (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5786:51)
    at u.consume (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:75)
    at u.consumed (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:236)
    at file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:117
[2020-12-04 20:37:07.551] [renderer1] [error] Unable to write to Workspace Settings because databricks.connection.default.databricksConnectJars is not a registered configuration.: Error: Unable to write to Workspace Settings because databricks.connection.default.databricksConnectJars is not a registered configuration.
    at k.reject (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5789:245)
    at k.resolveAndValidate (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5792:159)
    at k.doWriteConfiguration (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5786:275)
    at Object.factory (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5786:51)
    at u.consume (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:75)
    at u.consumed (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:236)
    at file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:117
[2020-12-04 20:37:07.552] [renderer1] [error] Unable to write to Workspace Settings because databricks.connection.default.pythonInterpreter is not a registered configuration.: Error: Unable to write to Workspace Settings because databricks.connection.default.pythonInterpreter is not a registered configuration.
    at k.reject (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5789:245)
    at k.resolveAndValidate (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5792:159)
    at k.doWriteConfiguration (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5786:275)
    at Object.factory (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5786:51)
    at u.consume (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:75)
    at u.consumed (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:236)
    at file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:137
[2020-12-04 20:37:07.552] [renderer1] [error] Unable to write to Workspace Settings because databricks.connection.default.port is not a registered configuration.: Error: Unable to write to Workspace Settings because databricks.connection.default.port is not a registered configuration.
    at k.reject (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5789:245)
    at k.resolveAndValidate (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5792:159)
    at k.doWriteConfiguration (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5786:275)
    at Object.factory (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5786:51)
    at u.consume (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:75)
    at u.consumed (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:236)
    at file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:137
[2020-12-04 20:37:07.552] [renderer1] [error] Unable to write to Workspace Settings because databricks.connection.default.organizationId is not a registered configuration.: Error: Unable to write to Workspace Settings because databricks.connection.default.organizationId is not a registered configuration.
    at k.reject (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5789:245)
    at k.resolveAndValidate (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5792:159)
    at k.doWriteConfiguration (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5786:275)
    at Object.factory (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5786:51)
    at u.consume (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:75)
    at u.consumed (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:236)
    at file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:137
[2020-12-04 20:37:07.552] [renderer1] [error] Unable to write to Workspace Settings because python.dataScience.codeRegularExpression is not a registered configuration.: Error: Unable to write to Workspace Settings because python.dataScience.codeRegularExpression is not a registered configuration.
    at k.reject (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5789:245)
    at k.resolveAndValidate (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5792:159)
    at k.doWriteConfiguration (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5786:275)
    at Object.factory (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5786:51)
    at u.consume (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:75)
    at u.consumed (file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:236)
    at file:///C:/Users/user3231/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:132:117
```

**Comment by petervandenabeele** [comment] 2020-12-04 19:57
![vscode-databricks-screenshot](https://user-images.githubusercontent.com/55656/101209008-50393f00-3673-11eb-9d5e-32fe0d97771e.png)

**Comment by gbrueckl** [comment] 2020-12-06 07:03
Hi Peter,

it seems like you are using an old version of the extension. 
The properties in question (databricks.connection.default.databricksConnectJars, databricks.connection.default.pythonInterpreter, databricks.connection.default.organizationId) have been removed some time ago and do not exist anymore in the current version.
They were initially supposed to do exactly what you would expected them to do - update your databricks-connect config and allow you to switch the databricks-connect config using this extensions.
However, this turned out to be more complicated than intially thought so this feature was removed and postponed to the future.

in general, this extension only does the synching for you but is not designed to execute the notebooks. Thats what you have databricks-connect for. So if you error is about connecting a (now local) notebook to a databricks cluster and execute it there, plelase seek help at databricks-connect

kind regards,
-gerhard

**Comment by gbrueckl** [comment] 2021-01-12 09:35
closing this issue as we have not received any further feedback and the issue is probably outdated anyway

**Closed by gbrueckl** 2021-01-12 09:35 UTC
