### ISSUE TITLE
All .py files duplicated as .ipynb 

### ISSUE THREAD

**Issue by lukaszmentel** [paiqo/Databricks-VSCode#167] opened 2023-07-26 14:05 UTC
Hey, first of all thanks for a great tool!

I managed to configure the extension and get access to remote repo. I pulled all the files (not sure what is the difference between `pull` in the repo section and `download` in the workspace section, but it's safe to assume I did both at some point.

I made changes locally to some files and since there is no` push` I used `upload` from the workspace section. Now comes the unexpected and unwanted situation that **all** my `.py` files in the (even the ones I didn't touch got converted to `.ipynb` and pushed to remote repo. 

Here's what I'm wondering:
1. how to reverse this situation while keeping the changes I made locally - obviously I don't want to convert all the files. Both the extension and databricks have pretty basic (insufficiently minimal) git/github interface so it's hard to figure out what a good move here.
2. Can I configure the extension to not convert any of the existing files and keep them as they are?

Thanks!

**Comment by gbrueckl** [comment] 2023-08-29 19:03
I will have a look at this once I am back at work next week.
It seems like the root cause is how notebooks and python files are treated 
I will report back here once I had a closer look

**Comment by gbrueckl** [comment] 2023-09-28 19:35
just found some time to have a look at this and I think I fixed the issue with v2.2.3 which is also live now in the VSCode Gallery

please give it another try and report back, thanks!

**Comment by gbrueckl** [comment] 2023-10-18 08:25
closing as fixed and no further feedback provided

**Closed by gbrueckl** 2023-10-18 08:25 UTC
