### ISSUE TITLE
Refreshing secrets lists errors out when it contains secrets the user does not have permissions to access.

### ISSUE THREAD

**Issue by dmoore247** [paiqo/Databricks-VSCode#43] opened 2020-11-25 03:33 UTC
There are 4 secret scopes user (me) doesn't have access to. I use vs-code extension to create new scope.
I hit refresh and I get error:
`<my email> does not have READ permission on scope <scope name> to perform this action.`

Refresh should expect that user does not have access to 0, 1, or more secret scopes (based on the the new secrets ACL feature) and continue to refresh the list ignoring the error(s).

Databricks workspace release: `v3.20`
extension version `v0.6.0`

**Comment by gbrueckl** [comment] 2020-11-25 14:44
hmm, actually I am just calling the API there to get a list of secret scopes and I would have assumed that only secret scopes are returned to which i have access

to you get the error when loading the secret scopes or when expanding one to which you do not have access?

**Comment by gbrueckl** [comment] 2021-01-12 09:45
@dmoore247  can you answer my previous question?

> do you get the error when loading the secret scopes or when expanding one to which you do not have access?

**Comment by gbrueckl** [comment] 2021-03-23 11:41
closing this as no further feedback was provided to track down the root cause

**Closed by gbrueckl** 2021-03-23 11:41 UTC
