### ISSUE TITLE
Notebook plots not displayed

### ISSUE THREAD

**Issue by tsveiga** [paiqo/Databricks-VSCode#179] opened 2023-11-20 12:36 UTC
Hi! Referring back to issue #162. I left a comment in there but not quite sure if that will be notified, so decided to open a new issue for visibility. Feel free to close if I am unnecessarily creating duplicates.

I am experiencing the same behavior as described by the above users, although without any errors. Taking the basic example given before, the cell outputs only the handle of the plot.

![bilde](https://github.com/paiqo/Databricks-VSCode/assets/45718165/35273cf5-121b-4d30-8bc6-ff866186c0ed)

After digging a bit, it seems that the raw file does not include the image data. This is the raw data for this cell, under "data" there should be an image field.

![bilde](https://github.com/paiqo/Databricks-VSCode/assets/45718165/dcd48551-d01f-4cdc-a9f2-295bc31ba950)

Furthermore, if I run the cell directly in Databricks through the browser UI and download it afterwards, then the downloaded notebook includes the image data and it gets properly displayed. Also, if I run the notebook locally then it is fine as well.

I am using VSCode v1.84.2 on Windows 10 with the latest extension version, but have tried on a setup with Linux Mint with the same behavior.
Thankful if we can get some pointers on this. (and btw, great and very helpful extension you developed here!)

**Comment by mdrobena** [comment] 2023-11-20 23:26
Hi, I have been going through the same issue for a while now. I am experiencing the same behaviour as described by @tsveiga. My setup is:

- wsl/windows 10
- vscode v1.84.2
- databricks power tools v2.2.3
- jupyter v2023.10.1100000000

I run the same code example:
```
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(20, 5))
x = [0, 10, 50, 100, 200]
y = [23, 21, 1,2 , 3]
ax.plot(x , y)
```
 on two different single nodes in two seperate Azure Databricks workspaces:

- node 1 runtime is 13.3 LTS ML
- node 2 runtime is 14.1 ML

The result rendered back is in the form of:

`
[<matplotlib.lines.Line2D at 0x7fc2a495cfa0>]
`

**Comment by gbrueckl** [comment] 2023-11-21 08:30
while I fully understand the problem, I dont think there is an easy solution for this - at least not something that can be implemented as part of this extension.
we obtain the results from the Databricks Execution API (https://docs.databricks.com/api/workspace/commandexecution/commandstatus) which only returns the result that you see (e.g. `[<matplotlib.lines.Line2D at 0x7fc2a495cfa0>]`) as a text

there are two potential solutions I could think of:
- Databricks changes this API to support `.plot(...)` and properly return an image (very unlikely as this API has not been touched for ages)
- you can somehow change your code to produce a real image or an HTML output, not sure if thats doable in your case(s)

**Comment by tsveiga** [comment] 2023-11-21 13:05
I did a few attempts, and it seems that the API only returns outputs of `text/plain` type. Html is not returned either...I haven't tried, but I guess a workaround might be to save figures into files and loading the file aftewards.
But I noticed that in the issue I referred to you got a plot from the basic example, while it looks like you are running the cell agains a Databricks cluster. Was there something different back then?

That's a bummer, as we need to do some data visualizations. Guess we will have to resort to the web UI whenever needed, while hoping that someone with better expertise can come up with a better solution.

**Comment by janosbiro** [comment] 2023-11-21 21:49
Hey - I have the same experience and wondering if we could come up with some workaround to solve that. The whole extension makes my life easier to work within vscode instead of the browser UI, but this is actually force me to use it. 

I tried to change in plotly renderers who render the image without any success - because I thought pyspark pandas creates a plotly output - so maybe we can use that output and render in vscode. Unfortunately changing it from databricks to sth ese did not help. I also tried to create some function to parse the output and create some plotly charts - but without any success until now.

Let me know if you have some idea or answers.

**Comment by tsveiga** [comment] 2023-11-22 09:33
I feel you @janosbiro, I am feeling exactly the same.

So far I have tried with no luck: 
 - return the image directly as html and then render the html in the notebook;
 - save the image to a file and load into into a markdown cell.

It seems that no matter what you do, Databricks only returns the cell outputs of type `text/plain` and the rest gets ignored.

**Comment by gbrueckl** [comment] 2023-11-23 21:08
I also just reviewed https://github.com/paiqo/Databricks-VSCode/issues/162 and tbh I am not sure why it used to work back then
the only thing I could think of is a different/older Databricks runtime with maybe an older version of `matplotlib `which rendered the output differently ?!

**Comment by gbrueckl** [comment] 2023-11-23 21:10
ok, I ran it successfully from VSCode with DBR 9.1 LTS
so it must have something to do with the installed version of one of the dependent libraries 

DBR 9.1 uses matplotlib          3.4.2
DBR 14.1 uses matplotlib               3.7.0

**Comment by gbrueckl** [comment] 2023-11-23 21:12
alternatively, you might also want to check out the official Databricks extension for VSCode
https://marketplace.visualstudio.com/items?itemName=databricks.databricks
which also supports notebooks now but does not use the API that we use but uses Spark Connect instead

**Comment by tsveiga** [comment] 2023-11-24 10:01
Thanks @gbrueckl, that's pretty helpful.
I went over all DBR versions. It works until 12.2 LTS, while any version after returns no image. Now I guess it is an art of guessing what the hell happened in between. 

As for the official DB extension, I had tried it before but, to be honest, is not nearly as intuitive as yours.

**Comment by janosbiro** [comment] 2023-12-05 13:41
Hey @gbrueckl @tsveiga  - I think I just figured out the workaround which works fine for me now. So I write here if it helps for further developement or if someone will look for a solution as well.

I couldn't understand why Vscode jupyter is not rendering html output so I played with the output. I think you can use display function from ipython.core.display to render it immediately the output.

So I'm using plotly for creating the output and do the following:
Option 1:
- You can use display( plotly code inside ) which renders your plot.
Option 2:
- Save the output of the chart into a variable and call the variable.

I'm going with option two since I have my own functions to create my plots. So basically i do the following
p1 = create_histogram( «This is a funtion that creates the plotly chart »)
p1

and p1 will be rendered without using any additional function.

I hope it helps for you as well.

**Comment by gbrueckl** [comment] 2024-01-22 22:11
closing this issue as its not related to this extension but the root cause is a change in Databricks

**Closed by gbrueckl** 2024-01-22 22:11 UTC

**Comment by rgalljamov** [comment] 2024-07-26 13:26
Hi @gbrueckl, 

Thank you for the incredible work! Your extension has the potential to be perfect. However, not being able to display plots is a significant issue for data scientists, and fixing it will ensure your awesome work brings the intended benefits and impact. Thus, I kindly ask you to reconsider looking into this issue.

I've prepared a [Jupyter notebook](https://drive.google.com/file/d/1Po1bSF_LdS22J7p9LorJZVmCNtneI4kC/view?usp=sharing) with comments for easy reproduction. It shows that the HTML text for a Plotly plot arrives correctly but isn't rendered properly, suggesting an easy fix, an issue on my side, or an issue in VS Code.

Alternatively, here is a minimal code example:
```import numpy as np
import plotly.graph_objects as go

# Generate random values
x = np.random.rand(100)
y = np.random.rand(100)

# Create and show the scatter plot
fig = go.Figure(data=go.Scatter(x=x, y=y, mode='markers', marker=dict(size=5, opacity=0.5)))
fig.show()
```


Thank you once again for your hard work and dedication.
Best regards,
Rustam

**Comment by gbrueckl** [comment] 2024-07-29 06:07
please check my [answer](https://github.com/paiqo/Databricks-VSCode/issues/179#issuecomment-1820450447) above

**Comment by rgalljamov** [comment] 2024-08-05 16:13
Hi @gbrueckl,

Thank you for your quick response. I've read your answer above and understand that when the Databricks API just returns text, there's nothing you can do. However, in the case of Plotly plots, the Databricks API returns proper HTML. This HTML is however not displayed correctly, which I think might be an easy fix on the extension's side.

Please see the attached screenshot showing the HTML output for a Plotly plot. To see the returned HTML code, I needed to change the presentation mode in VS Code to ``text/plain``. Sorry if I'm still misunderstanding something. If not, I would be happy if you might reconsider looking into this.

Thank you very much in advance and best regards,
Rustam
![databricks-powertools-interpreter-returns-html-but-it-is-not-displayed-annotated](https://github.com/user-attachments/assets/ae35eba1-41f3-4a9f-bb93-aaaf04382dbf)

**Comment by gbrueckl** [comment] 2024-08-06 13:30
yes, thats right, HTML code is returned by the Databricks REST API
but while it is HTML code, the actual logic is implemented as a script which I think does not work with the built-in renderer of VSCode for HTML
at least I have not found a way yet to make it display HTML scripts properly

the alternative would be to somehow make the API return an image but thats not my area of expertise

**Comment by rgalljamov** [comment] 2024-08-14 20:34
Thank you very much for your detailed reply, @gbrueckl! 
Totally see the limitations and appreciate you taking the time for explaining them in detail.
I hoped you might be in close contact with Databricks and might request that change in the REST API to ensure this crucial feature for data scientists. But I'm sure you have your priorities and totally respect them.

**Comment by anishazaveri** [comment] 2025-04-02 12:46
I love this extension but the lack of plots working is a huge problem
- Why do the extension docs say: 

> Depending on the output of the cell, the results are rendered accordingly - e.g. as text, as table or as image.

if the image capability doesn't work?
- Why does the image display seem to work [here](https://github.com/paiqo/Databricks-VSCode/pull/84). I could not reproduce this with a spark or a pandas df

- One workaround I thought of was a function that downloads the image locally and loads it. But it seems like [I can't access local files when connected to a databricks cluster](https://github.com/paiqo/Databricks-VSCode/issues/97)?

**Comment by gbrueckl** [comment] 2025-04-02 13:35
if you followed the comments above, the output of a cell depends on the code/library that creates the output as well as how/if the Databricks Execution API returns those outputs accordingly. Some libraries work well, some dont - there isnt really much I can do about it, neither from the way your code/library creates the output nor how the Databricks Execution API transmits the output the the client (=vscode)

to download the image locally, we would first need to know where the image is stored (on Databricks) and again, for this to work your code/library would need support to write the output to a file (on Databricks)
