### ISSUE TITLE
Workspace folder content not displayed if it contains files of unknown formats

### ISSUE THREAD

**Issue by demattia** [paiqo/Databricks-VSCode#32] opened 2020-08-05 21:13 UTC
When clicking on a folder in the Workspace area, if the folder contains a file of unknown format the error `Cannot read property 'extension' of undefined` is returned and the content of the folder is not displayed.

Example: If a folder includes both notebook files and a wheel file for a library that was installed in the cluster the whole folder content will not be displayed.

Desired behavior: Either ignore the unknown files or show them and make them "online only". Alternatively, allow defining exportFormats for other file formats.

Workaround: Keep only files of known format in folders that need to be accessible to the extension.

**Comment by gbrueckl** [comment] 2020-08-06 05:43
Is the .wheel file in your online folder or in your local folder?
If it is online it *should* be displayed as a library in VSCode which also cannot be downloaded

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gbrueckl** [comment] 2020-08-06 06:45
just ran some quick tests and it is as I have written above. 
if you have local file that does not match the file extensions configured in the ExportFormats, you will get a warning that the .whl file cannot be loaded:
`..\numpy.whl has no valid extension and will be ignored! Supported extensions can be confiugred using setting 'exportFormats'.`

however, all the other content displays just fine
can you give me a bit more details whats not working in your scenario?

**Comment by demattia** [comment] 2020-08-12 16:27
Thank you very much for checking. I am still running into the same issue. I am connecting to a cluster in eastus.databricks.net and the file is in the online folder. When I try to open the folder containing the whl files I still get the `Cannot read property 'extension' of undefined` error. I moved the whl files into a subfolder so I can still access the notebook files. However, when I try to open the subfolder I still get the same error. I get the same error if I try to download the folder.

What other information could be useful to debug the issue?

**Comment by gbrueckl** [comment] 2020-08-13 07:38
can you make sure you have the latest version installed (1.0.4.)?

**Comment by gbrueckl** [comment] 2020-08-14 07:07
here is a screenshot of how it looks in my environment when a .whl file/library exists online:
![image](https://user-images.githubusercontent.com/11884402/90223017-85442c00-de0d-11ea-9d91-4c63b479ef0e.png)
as you can see it is displayed as "Library" with the specific icon and there is no option to download it

**Comment by demattia** [comment] 2020-08-18 21:32
Interesting, I have a similar structure. I can see the folder in the extension (apologies for not posting screenshots, it is a work environment), though it is under my username folder:
`Workspace/Users/myusername/Library`

Inside the library folder I have four versions of the same library. This is a custom library in whl format. The name is of the form:

`LIBRARYNAME-1.0.0-py3-none-any.whl`
`LIBRARYNAME-1.0.1-py3-none-any.whl`
`LIBRARYNAME-1.0.2-py3-none-any.whl`
`LIBRARYNAME-1.0.3-py3-none-any.whl`

I can see the folder and its content in the Databricks web page (this is an Azure Databricks instance in case it makes any difference). However, when I try to open the same folder in the extension I get the error `Cannot read property 'extension' of undefined` pop up in the bottom left of VSCode and I do not get any content displayed in the Workspace view on the left side.

I am currently using VSCode version 1.41.1 and the latest version of the extension. I can try to update VSCode if you think that may help?

**Comment by demattia** [comment] 2020-08-18 21:50
I just noticed that the extension version is 2.5. This may be due to my older VSCode version? I will try to update and see if I can install the latest version of the extension.

**Comment by gbrueckl** [comment] 2020-08-19 06:43
so the latest version of the extension is 0.6.0
VSCode versino should not matter that much but for safety make sure you use a recent one not older than 2 months (it is usually updated automatically anyway)

unfortunately I still cannot reproduce your issues :(
![image](https://user-images.githubusercontent.com/11884402/90601147-04fc3d00-e1f8-11ea-814b-4b8bd255a622.png)
![image](https://user-images.githubusercontent.com/11884402/90601169-0fb6d200-e1f8-11ea-8588-d530ad14e25c.png)

**Comment by demattia** [comment] 2020-08-19 13:44
Indeed, it was the version. After updating everything I see the library without any issues. Thank you very much for following up with me! Great job with this extension!

**Comment by gbrueckl** [comment] 2020-08-20 08:58
great, closing this issue then!

**Closed by gbrueckl** 2020-08-20 08:58 UTC
