### ISSUE TITLE
Unable to double click file to open

### ISSUE THREAD

**Issue by vfortierdatabricks** [paiqo/Databricks-VSCode#2] opened 2020-02-25 14:46 UTC
Using VSCode for mac version 1.42.1 with the plugin version 0.1.0. The plugin can connect and download the files OK and I see them in the folder I specified but if I double click on files to open them, I just see a message at the bottom saying: Opening a local cached file. To open the most recent file from Databricks, please manually download it first!

I verified and in the folder, the full file is downloaded (I opened it in textedit to see the content)

**Comment by gbrueckl** [comment] 2020-02-25 16:13
hi @vfortierdatabricks ,
this is actually by design - let me explain:
once you download/sync the notebook, there are two versions - your local one and the one stored in the databricks workspace. From now on, by default you will open the local copy whenever you click on a notebook in the Workspace browser of the VS Code extension. 
Otherwise, if we always download the latest version from databricks, we would not be able to modify the file locally and upload it again to databricks. I can you really want to get the latest version from Databricks, you can manually download it again.

The warning that pops up is just informing you about this.

**Comment by gbrueckl** [comment] 2020-02-25 16:22
with regards to double-click vs. single-click please have a look at the setting
"workbench.list.openMode": "doubleClick" | "singleClick" 
which can be added to your settings
by default, a file is downloaded/opened on a single click but you can change this via the setting above. This is not related to the extension itself but is a general VS Code setting

**Comment by vfortierdatabricks** [comment] 2020-02-25 18:43
Thanks for the quick answer but the issue I have is no matter what option I use (double or single click), the file never opens in VS Code. it does not open a new tab in the editor with that file.

**Comment by gbrueckl** [comment] 2020-02-25 20:03
What happens if you use explorer to navigate to where the synced file is stored and open it directly in VS code? (that's basically what happens under the hood)
Also, do you have the Python extension from Microsoft installed?

**Comment by vfortierdatabricks** [comment] 2020-02-25 20:12
If I drag and drop the file that was downloaded, it opens it (it's an .ipynb file) and display it as a notebook but seems to be asking for a jupyter cluster.

I have the python extension from microsoft version 2020.2.64397

**Comment by gbrueckl** [comment] 2020-02-25 20:47
Do you have jupyter notebooks installed? E. G. Via Anaconda?

**Comment by vfortierdatabricks** [comment] 2020-02-25 20:51
No, nothing like that installed. And the only 2 extensions I have in VS Code are Databricks VS Code and Python.

**Comment by gbrueckl** [comment] 2020-02-25 21:03
Do the "Show Definition" buttons for jobs/cluster work? They use the same code to open a (temporary) file

**Comment by vfortierdatabricks** [comment] 2020-02-25 22:10
If it is the show json definition in both cluster and jobs, it does work and opens a json file

**Comment by gbrueckl** [comment] 2020-02-26 05:48
Is there anything specific about the notebook you want to open?
Is it super big? 
Do you see any other messages popping up at the right bottom corner except that one warning?

**Comment by vfortierdatabricks** [comment] 2020-02-26 12:23
All notebooks tried were in the 5-10 cell length, less than 2k sometimes (the ipynb file).

The first time I click on a file, it says download of time... the file downloads OK but does not show. the second time it just says opening from cache.

**Comment by gbrueckl** [comment] 2020-02-26 16:46
sounds very strange to me and to be honest I am running out of ideas :(

I am just reworking some parts of the workspace browser and it may work with the next version also for you (actually you are the first one reporting this or a similar issue)

**Comment by vfortierdatabricks** [comment] 2020-02-26 16:47
No worries, I'll monitor the project and test the next version for sure! Thanks for the help

**Comment by gbrueckl** [comment] 2020-02-26 17:09
does it work with non-.iypnb files? e.g. .r, .sql or .scala files?

**Comment by vfortierdatabricks** [comment] 2020-02-26 17:32
.sql files have the same behavior so far, download but not open

**Comment by gbrueckl** [comment] 2020-02-27 19:20
just published a new version - please give it a try

**Comment by vfortierdatabricks** [comment] 2020-02-27 19:53
Exact same behavior with the new plugin.
If it helps, here is the information in the about box of VS Code

Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0

**Comment by gbrueckl** [comment] 2020-03-05 13:48
I assume it is related to your OS 
is this actually Linux or Mac/Apple ?!
could be that there is something wrong with the path when referencing the downloaded file - can you check the information message that pops up when you download a notebook manually?
does it look like a valid (relative) path?

**Comment by vfortierdatabricks** [comment] 2020-03-05 14:09
The OS is MacOS

The file downloads to the path I selected.

the display shows the full path that is in the workspace but does not show the path on my local machine.

**Comment by gbrueckl** [comment] 2020-03-05 15:25
the question was more about whether the delimiters in the path "/" vs. "\" are correct (actually I do not knot the filesystem on MacOS)

**Comment by vfortierdatabricks** [comment] 2020-03-05 15:27
To make sure, I created a new folder /tmp/vscode/ and tried both with the trailing / (/tmp/vscode/) and without (/tmp/vscode ) and the issue is still there.

**Comment by vfortierdatabricks** [comment] 2020-03-05 15:39
Found the issue! I used the dev tools in VSCode and found that if I put the directory to /tmp/vscode it would give me this error: stack trace: Error: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//") 

So the path for the directory cannot start with a /

removing the / made it worked.

**Comment by gbrueckl** [comment] 2020-03-05 15:41
cool :)
really happy it finally worked for you!

I will close the issue then

**Closed by gbrueckl** 2020-03-05 15:41 UTC
