### ISSUE TITLE
ipynb files are shown as raw json

### ISSUE THREAD

**Issue by mhansinger** [paiqo/Databricks-VSCode#63] opened 2021-10-19 15:47 UTC
The databricks extension shows the .ipynb notebooks from my workspace as raw json files and not as a proper jupyter notebook, as I would've expected. 
However, when I open the same files in the explorer from the sync directory (where my workspace is downloaded), they are showen the correct way as notebooks. 
In my ```settings.json``` I've included:
```
    "databricks.connection.default.exportFormats": {
        "Scala": ".scala",
        "Python": ".ipynb",
        "SQL": ".sql",
        "R": ".r"
      }
```

Am I missing something out?

**Comment by mhansinger** [comment] 2021-10-20 14:21
Thanks @gbrueckl ,
in fact the Python extension is installed and I'm generally able to correctly disply .py and .ipynb files.
It's just weird that opening the .ipynb files from the workspace within the Databricks extension I get them displayed as raw json files.
Thanks, Max

**Comment by AlexPapas** [comment] 2021-12-24 07:08
Is this resolved? I face the same issue :/

**Comment by gbrueckl** [comment] 2022-01-03 10:31
I think I finally found the root cause of this and will publish a new version today!

**Comment by gbrueckl** [comment] 2022-03-29 13:47
fixed with recent release

**Closed by gbrueckl** 2022-03-29 13:47 UTC
